apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sc--nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sc--nginx
  template:
    metadata:
      labels:
        app: sc--nginx
    spec:
      containers:
        - name: sc--nginx
          image: library/nginx:1.19.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
      restartPolicy: Always
