apiVersion: v1
kind: Pod
metadata:
  name: sc--nginx
spec:
  containers:
    - name: sc--nginx
      image: library/nginx:1.19.1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          protocol: TCP
          name: http
  restartPolicy: Always
